### ISSUE TITLE
few questions about current code

### ISSUE THREAD

**Issue by gudovskiy** [sinhasam/vaal#5]
Hello, could you answer these questions:
1. Why there are no separate val/train transformers? For example, does ImageNet need to replace random transforms with these: transforms.Resize(256), transforms.CenterCrop(224)?
2. What's the VAE architecture for ImageNet with 224x224 inputs? Currently, only 32x32 is given
3. Do you plan to release code for segmentation task?

**Comment by sinhasam** [comment]
Yes you are correct about the transformers.

We are trying to release the code for the segmentation task, as well as the VAE architectures, and checking the old code to ensure they are consistent with the experiments ran. For ImageNet the inputs were resized to 32x32 for the VAE model.

**Comment by PrateekMunjal** [comment]
[Regarding Imagenet] Hi, can you explain the reason for using global imagenet statistics (mean and stdev) in imagenet transforms [[here](https://github.com/sinhasam/vaal/blob/master/custom_datasets.py#L13)]? I am confused because in your experiments you start training with only 10% of data, therefore why are we standardizing our 10% data with global statistics ? -- Shouldn't we calculate the mean and stddev separately for this 10% data ?
