### ISSUE TITLE
Results about Caltech-256

### ISSUE THREAD

**Issue by apolaris** [sinhasam/vaal#8]
Hello,
When I reproduce the results on Caltech-256, I found that nearly no classification model can reach 90% Acc-rate on that dataset and 85% Acc-rate is also very difficult with special data augmentation algorithm and very deep network. Can you release your code for Caltech-256?
Thank you.

**Comment by sinhasam** [comment]
Thanks for your interest in our work. On first thought, it might be possible that we misreported the results of Caltech-101 as Caltech-256. I will look at the exact data used and change the paper accordingly ASAP if that is indeed the issue. Otherwise, I will add the dataloader code for Caltech-256.
